create database dbp1;

use dbp1;

CREATE TABLE CUENTA (
    ident   VARCHAR (50) NOT NULL,
    nombre  VARCHAR (100) NOT NULL,
    empresa VARCHAR (50),
    dominio VARCHAR (50) NOT NULL,
    pass    VARCHAR (50) NOT NULL
	CONSTRAINT CUENTA_PK PRIMARY KEY (ident)
);

CREATE TABLE CARPETA (
    codigo         INTEGER NOT NULL IDENTITY(1,1),
	nivel          INTEGER NOT NULL,
    nombre         VARCHAR (50) NOT NULL,
    tipo           VARCHAR (50) NOT NULL,
    CUENTA_ident   VARCHAR (50) NOT NULL,
    CARPETA_codigo INTEGER,
	CONSTRAINT CARPETA_TIPO_CH CHECK (tipo = 'privado' or tipo = 'publico'),
	CONSTRAINT CARPETA_PK PRIMARY KEY (codigo),
	CONSTRAINT CARPETA_CUENTA_FK FOREIGN KEY (CUENTA_ident) REFERENCES CUENTA (ident) ON DELETE CASCADE,
	CONSTRAINT CARPETA_CARPETA_FK FOREIGN KEY (CARPETA_codigo) REFERENCES CARPETA (codigo)
);

CREATE TABLE MENSAJE (
    codigo INTEGER NOT NULL IDENTITY(1,1),
    asunto VARCHAR (50),
    texto  VARCHAR (256),
	CONSTRAINT MENSAJE_PK PRIMARY KEY (codigo)
);

CREATE TABLE MSG (
    codigo         INTEGER NOT NULL IDENTITY(1, 1),
    fecha          DATETIME NOT NULL,
    estado         INTEGER NOT NULL,
    tipo           VARCHAR (50) NOT NULL,
    CUENTA_ident   VARCHAR (50) NOT NULL,
    CARPETA_codigo INTEGER NOT NULL,
    MENSAJE_codigo INTEGER NOT NULL,
    lista          INTEGER NULL,
    CONSTRAINT MSG_TIPO_CH CHECK (tipo = 'para' or tipo = 'cc' or tipo = 'bcc'),
    CONSTRAINT MSG_ESTADO_CH CHECK (estado = 0 or estado = 1),
    CONSTRAINT MSG_PK PRIMARY KEY (codigo),
    --CONSTRAINT MSG_PK PRIMARY KEY (CUENTA_ident, CARPETA_codigo, MENSAJE_codigo),
    CONSTRAINT MSG_CARPETA_FK FOREIGN KEY (CARPETA_codigo) REFERENCES CARPETA (codigo) ON DELETE CASCADE,
    CONSTRAINT MSG_CUENTA_FK FOREIGN KEY (CUENTA_ident) REFERENCES CUENTA (ident),
    CONSTRAINT MSG_MENSAJE_FK FOREIGN KEY (MENSAJE_codigo) REFERENCES MENSAJE (codigo) ON DELETE CASCADE
);
ALTER TABLE MSG ALTER COLUMN lista VARCHAR(256) NOT NULL;

CREATE TABLE ARCHIVO (
	codigo         INTEGER NOT NULL IDENTITY(1,1),
    ruta           VARCHAR (100) NOT NULL ,
    MENSAJE_codigo INTEGER NOT NULL,
    CONSTRAINT ARCHIVO_PK PRIMARY KEY (codigo),
	CONSTRAINT ARCHIVO_MENSAJE_FK FOREIGN KEY (MENSAJE_codigo) REFERENCES MENSAJE (codigo) ON DELETE CASCADE
);

DROP TABLE ARCHIVO;
DROP TABLE MSG;
DROP TABLE MENSAJE;
DROP TABLE CARPETA;
DROP TABLE CUENTA;

use dbp1;

SELECT * FROM CUENTA;
SELECT * FROM CARPETA;
SELECT * FROM MENSAJE;
SELECT * FROM MSG;
SELECT * FROM ARCHIVO;

DELETE FROM MSG;
DELETE FROM MENSAJE;


SELECT dbo.obtener_carpeta ('entrada', 'id2', '', 0);



























ALTER TABLE MSG ADD COLUMN codigo INTEGER NOT NULL IDENTITY(1,1);

CREATE TABLE MSG (
    codigo         INTEGER NOT NULL IDENTITY(1, 1),
    fecha          DATETIME NOT NULL,
    estado         INTEGER NOT NULL,
    tipo           VARCHAR (50) NOT NULL,
    CUENTA_ident   VARCHAR (50) NOT NULL,
    CARPETA_codigo INTEGER NOT NULL,
    MENSAJE_codigo INTEGER NOT NULL,
    lista          INTEGER NULL,
    CONSTRAINT MSG_TIPO_CH CHECK (tipo = 'para' or tipo = 'cc' or tipo = 'bcc'),
    CONSTRAINT MSG_ESTADO_CH CHECK (estado = 0 or estado = 1),
    CONSTRAINT MSG_PK PRIMARY KEY (codigo),
    --CONSTRAINT MSG_PK PRIMARY KEY (CUENTA_ident, CARPETA_codigo, MENSAJE_codigo),
    CONSTRAINT MSG_CARPETA_FK FOREIGN KEY (CARPETA_codigo) REFERENCES CARPETA (codigo) ON DELETE CASCADE,
    CONSTRAINT MSG_CUENTA_FK FOREIGN KEY (CUENTA_ident) REFERENCES CUENTA (ident),
    CONSTRAINT MSG_MENSAJE_FK FOREIGN KEY (MENSAJE_codigo) REFERENCES MENSAJE (codigo) ON DELETE CASCADE
);