
DROP TABLE ASIGNACION_ARBITRO;
DROP TABLE ASIGNACION_GRUPO;
DROP TABLE ARBITRO;
DROP TABLE GRUPO;
DROP TABLE PRONOSTICO;
DROP TABLE PARTIDO;
DROP TABLE CIUDAD;
DROP TABLE JUGADOR;
DROP TABLE EQUIPO;
DROP TABLE PAIS;
DROP TABLE CONFEDERACION;

CREATE TABLE PAIS (
    codpais                        INTEGER NOT NULL IDENTITY(1, 1) ,
    nombre                         VARCHAR (50) NOT NULL ,
    CONSTRAINT PAIS_PK PRIMARY KEY ( codpais ) ,
    CONSTRAINT PAIS_nombre_UN UNIQUE ( nombre ) ,
);

CREATE TABLE CIUDAD (
    codciudad INTEGER NOT NULL IDENTITY(1, 1) ,
    nombre    VARCHAR (50) NOT NULL ,
    CONSTRAINT CIUDAD_PK PRIMARY KEY ( codciudad ) ,
    CONSTRAINT CIUDAD_nombre_UN UNIQUE ( nombre )
);

CREATE TABLE ARBITRO (
    codarbitro INTEGER NOT NULL IDENTITY(1, 1) ,
    nombre     VARCHAR (50) NOT NULL ,
    CONSTRAINT ARBITRO_PK PRIMARY KEY ( codarbitro ) ,
    CONSTRAINT ARBITRO_nombre_UN UNIQUE ( nombre )
);

CREATE TABLE CONFEDERACION (
    codconfederacion INTEGER NOT NULL IDENTITY(1, 1) ,
    nombre           VARCHAR (50) NOT NULL ,
    CONSTRAINT CONFEDERACION_PK PRIMARY KEY ( codconfederacion ) ,
    CONSTRAINT CONFEDERACION_nombre_UN UNIQUE ( nombre )
);

CREATE TABLE GRUPO (
    codgrupo INTEGER NOT NULL IDENTITY(1, 1) ,
    nombre   VARCHAR (50) NOT NULL ,
    CONSTRAINT GRUPO_PK PRIMARY KEY ( codgrupo ) ,
    CONSTRAINT GRUPO_nombre_UN UNIQUE ( nombre )
);

CREATE TABLE USUARIO (
    nombre           VARCHAR (50) NOT NULL ,
    apellido         VARCHAR (50) NOT NULL ,
    edad             INTEGER NOT NULL  ,
	monto_pagado	 BIT NOT NULL ,
    puntos           INTEGER ,
	rol				 VARCHAR (50) NOT NULL ,
    PAIS_codpais     INTEGER NOT NULL ,
    CONSTRAINT USUARIO_PK PRIMARY KEY ( nombre ) ,
	CONSTRAINT USUARIO_ROL CHECK ( rol = 'participante' or rol = 'administrador' ) ,
    CONSTRAINT USUARIO_PAIS_FK FOREIGN KEY ( PAIS_codpais )
    REFERENCES PAIS ( codpais ) ON DELETE CASCADE
);
ALTER TABLE USUARIO ALTER COLUMN apellido VARCHAR(50) NULL;

--ALTER TABLE PARTICIPANTE ADD DEFAULT 'participante' FOR rol;
--ALTER TABLE PARTICIPANTE ADD CONSTRAINT PARCH_ROL CHECK ( rol = 'participante' or rol = 'administrador');

CREATE TABLE EQUIPO (
    codequipo    INTEGER NOT NULL IDENTITY(1, 1) ,
    nombre       VARCHAR (50) NOT NULL ,
    CONF_codconf INTEGER NOT NULL ,
    CONSTRAINT EQUIPO_PK PRIMARY KEY ( codequipo ) ,
    CONSTRAINT EQUIPO_nombre_UN UNIQUE ( nombre ) ,
    CONSTRAINT EQUIPO_CONF_FK FOREIGN KEY ( CONF_codconf ) REFERENCES CONFEDERACION ( codconfederacion ) ON DELETE CASCADE
);

ALTER TABLE EQUIPO ALTER COLUMN CONF_codconf INTEGER NULL;
ALTER TABLE JUGADOR DROP CONSTRAINT JUGADOR_PK;
ALTER TABLE JUGADOR ADD CONSTRAINT JUGADOR_PK PRIMARY KEY ( nocamisola, EQUIPO_codequipo );

CREATE TABLE JUGADOR (
    nocamisola       INTEGER NOT NULL ,
	posicion		 VARCHAR (5) NOT NULL ,
    nombre           VARCHAR (50) NOT NULL ,
    fecha_nac        DATE NOT NULL ,
    estatura         NUMERIC (10,2) NOT NULL ,
    peso             NUMERIC (10,2) NOT NULL ,
	goles            INTEGER NOT NULL ,
    EQUIPO_codequipo INTEGER NOT NULL ,
    CONSTRAINT JUGADOR_PK PRIMARY KEY ( nocamisola ) ,
    CONSTRAINT JUGADOR_EQUIPO_FK FOREIGN KEY ( EQUIPO_codequipo )
    REFERENCES EQUIPO ( codequipo ) ON DELETE CASCADE
);

ALTER TABLE JUGADOR ALTER COLUMN fecha_nac DATE NULL;

CREATE TABLE PRONOSTICO (
    fecha                   DATE NOT NULL ,
    hora                    DATE NOT NULL ,
	USUARIO_nombre          VARCHAR (50) NOT NULL ,
	EQUIPO_codequipo1       INTEGER NOT NULL ,
    EQUIPO_codequipo2       INTEGER NOT NULL ,
    marcador1               INTEGER NOT NULL ,
    marcador2               INTEGER NOT NULL ,
    apuesta                 NUMERIC (10,2) ,
	puntos					INTEGER NOT NULL ,
    CONSTRAINT PRONOSTICO_PK PRIMARY KEY ( EQUIPO_codequipo1, EQUIPO_codequipo2, fecha, hora, USUARIO_nombre ) ,
    CONSTRAINT PRONOSTICO_EQUIPO_FK1 FOREIGN KEY ( EQUIPO_codequipo1 ) REFERENCES EQUIPO ( codequipo ) ,
    CONSTRAINT PRONOSTICO_EQUIPO_FK2 FOREIGN KEY ( EQUIPO_codequipo2 ) REFERENCES EQUIPO ( codequipo ) ,
    CONSTRAINT PRONOSTICO_PARTICIPANTE_FK FOREIGN KEY ( USUARIO_nombre ) REFERENCES USUARIO ( nombre ) ON DELETE CASCADE
);

ALTER TABLE PRONOSTICO DROP CONSTRAINT PRONOSTICO_PK;
ALTER TABLE PRONOSTICO ALTER COLUMN hora DATETIME NOT NULL;
ALTER TABLE PRONOSTICO ADD CONSTRAINT PRONOSTICO_PK PRIMARY KEY ( EQUIPO_codequipo1, EQUIPO_codequipo2, fecha, hora, USUARIO_nombre );

CREATE TABLE PARTIDO (
    fecha             DATE NOT NULL ,
    hora              DATE NOT NULL ,
    marcador1         INTEGER NOT NULL ,
    marcador2         INTEGER NOT NULL ,
    EQUIPO_codequipo2 INTEGER NOT NULL ,
    EQUIPO_codequipo1 INTEGER NOT NULL ,
    CIUDAD_codciudad  INTEGER NOT NULL ,
    CONSTRAINT PARTIDO_PK PRIMARY KEY ( EQUIPO_codequipo1, EQUIPO_codequipo2, fecha, hora ) ,
    CONSTRAINT PARTIDO_CIUDAD_FK FOREIGN KEY ( CIUDAD_codciudad ) REFERENCES CIUDAD ( codciudad ) ON DELETE CASCADE ,
    CONSTRAINT PARTIDO_EQUIPO_FK1 FOREIGN KEY ( EQUIPO_codequipo1 ) REFERENCES EQUIPO ( codequipo ) ,
    CONSTRAINT PARTIDO_EQUIPO_FK2 FOREIGN KEY ( EQUIPO_codequipo2 ) REFERENCES EQUIPO ( codequipo )
);
ALTER TABLE PARTIDO ADD puntos INTEGER NULL;
ALTER TABLE PARTIDO DROP CONSTRAINT PARTIDO_PK;
ALTER TABLE PARTIDO ALTER COLUMN hora DATETIME NOT NULL;
ALTER TABLE PARTIDO ADD CONSTRAINT PARTIDO_PK PRIMARY KEY ( EQUIPO_codequipo1, EQUIPO_codequipo2, fecha, hora );

ALTER TABLE PARTIDO ALTER COLUMN marcador1 INTEGER NULL;
ALTER TABLE PARTIDO ALTER COLUMN marcador2 INTEGER NULL;

CREATE TABLE ASIGNACION_GRUPO (
    puntos           INTEGER NOT NULL DEFAULT 0 ,
    EQUIPO_codequipo INTEGER NOT NULL ,
    GRUPO_codgrupo   INTEGER NOT NULL ,
    CONSTRAINT ASIGNACION_GRUPO_PK PRIMARY KEY ( EQUIPO_codequipo, GRUPO_codgrupo ) ,
    CONSTRAINT ASIGNACION_GRUPO_EQUIPO_FK FOREIGN KEY ( EQUIPO_codequipo ) REFERENCES EQUIPO ( codequipo ) ON DELETE CASCADE ,
    CONSTRAINT ASIGNACION_GRUPO_GRUPO_FK FOREIGN KEY ( GRUPO_codgrupo ) REFERENCES GRUPO ( codgrupo ) ON DELETE CASCADE
);

CREATE TABLE ASIGNACION_ARBITRO (
    ARBITRO_codarbitro        INTEGER NOT NULL ,
    tipo_arbitro              VARCHAR (50) NOT NULL ,
    PARTIDO_EQUIPO_codequipo2 INTEGER NOT NULL ,
    PARTIDO_EQUIPO_codequipo1 INTEGER NOT NULL ,
    PARTIDO_fecha             DATE NOT NULL ,
    PARTIDO_hora              DATE NOT NULL ,
    CONSTRAINT ASIGNACION_ARBITRO_PK PRIMARY KEY ( ARBITRO_codarbitro, PARTIDO_EQUIPO_codequipo1, PARTIDO_EQUIPO_codequipo2, PARTIDO_fecha, PARTIDO_hora ) ,
    CONSTRAINT ASIGNACION_ARBITOR_PARTIDO_FK FOREIGN KEY ( PARTIDO_EQUIPO_codequipo1, PARTIDO_EQUIPO_codequipo2,  PARTIDO_fecha, PARTIDO_hora ) 
    REFERENCES PARTIDO ( EQUIPO_codequipo1, EQUIPO_codequipo2, fecha, hora ) ON DELETE CASCADE ,
    CONSTRAINT ASIGNACION_ARBITRO_ARBITRO_FK FOREIGN KEY ( ARBITRO_codarbitro ) REFERENCES ARBITRO ( codarbitro ) ON DELETE CASCADE
);

ALTER TABLE ASIGNACION_ARBITRO ADD CONSTRAINT ASIGNACION_ARBITRO_PK PRIMARY KEY ( ARBITRO_codarbitro, PARTIDO_EQUIPO_codequipo1, PARTIDO_EQUIPO_codequipo2, PARTIDO_fecha, PARTIDO_hora );
ALTER TABLE ASIGNACION_ARBITRO ADD CONSTRAINT ASIGNACION_ARBITOR_PARTIDO_FK FOREIGN KEY ( PARTIDO_EQUIPO_codequipo1, PARTIDO_EQUIPO_codequipo2,  PARTIDO_fecha, PARTIDO_hora ) 
    REFERENCES PARTIDO ( EQUIPO_codequipo1, EQUIPO_codequipo2, fecha, hora ) ON DELETE CASCADE;

ALTER TABLE ASIGNACION_ARBITRO ALTER COLUMN PARTIDO_hora DATETIME NOT NULL;