create database dbp2;

use dbp2;

CREATE TABLE CONFEDERACION (
    idconfederacion INTEGER NOT NULL IDENTITY(1, 1) ,
    nombre          VARCHAR (100) NOT NULL ,
    CONSTRAINT CONFEDERACION_PK PRIMARY KEY ( idconfederacion ) ,
	CONSTRAINT CONF_NOMBRE_UN	UNIQUE ( nombre )
);

CREATE TABLE CIUDAD (
    idciudad INTEGER NOT NULL IDENTITY(1, 1) ,
    nombre   VARCHAR (100) NOT NULL ,
	CONSTRAINT CIUDAD_PK PRIMARY KEY ( idciudad ) ,
	CONSTRAINT CIUD_NOMBRE_UN UNIQUE ( nombre )
);

CREATE TABLE PAIS (
    idpais                        INTEGER NOT NULL IDENTITY(1, 1) ,
    nombre                        VARCHAR (50) NOT NULL ,
    CONFEDERACION_id			  INTEGER ,
    CONSTRAINT PAIS_PK PRIMARY KEY ( idpais ) ,
	CONSTRAINT PAIS_NOMBRE_UN UNIQUE ( nombre ) ,
	CONSTRAINT PAIS_CONFE_FK FOREIGN KEY ( CONFEDERACION_id ) REFERENCES CONFEDERACION ( idconfederacion ) ON
	DELETE CASCADE
);

CREATE TABLE ARBITRO (
    idarbitro   INTEGER NOT NULL IDENTITY(1, 1) ,
    nombre      VARCHAR (50) NOT NULL ,
    PAIS_idpais INTEGER NOT NULL ,
    CONSTRAINT ARBITRO_PK PRIMARY KEY ( idarbitro ) ,
	CONSTRAINT ARBITRO_PAIS_FK FOREIGN KEY ( PAIS_idpais ) REFERENCES PAIS ( idpais ) ON
	DELETE CASCADE
);

CREATE TABLE PARTICIPANTE (
    idparticipante   INTEGER NOT NULL IDENTITY(1, 1) ,
    nombre           VARCHAR (50) NOT NULL ,
    monto_inicial    NUMERIC (10,2) NOT NULL ,
    fecha_nacimiento DATE NOT NULL ,
    PAIS_idpais      INTEGER NOT NULL ,
	CONSTRAINT PARTICIPANTE_PK PRIMARY KEY ( idparticipante ) ,
	CONSTRAINT PARTICIPANTE_PAIS_FK FOREIGN KEY ( PAIS_idpais ) REFERENCES PAIS ( idpais ) ON 
	DELETE CASCADE
);

CREATE TABLE EQUIPO (
    idequipo    INTEGER NOT NULL IDENTITY(1, 1) ,
    nombre      VARCHAR (50) NOT NULL ,
    PAIS_idpais INTEGER NOT NULL ,
	CONSTRAINT EQUIPO_PK PRIMARY KEY ( idequipo ) ,
	CONSTRAINT EQUIPO_PAIS_FK FOREIGN KEY ( PAIS_idpais ) REFERENCES PAIS ( idpais ) ON
	DELETE CASCADE
);

CREATE TABLE JUGADOR (
    nocamisola       INTEGER NOT NULL ,
    fecha_nacimiento DATE NOT NULL ,
    estatura         NUMERIC (10,2) NOT NULL ,
    peso             NUMERIC (10,2) NOT NULL ,
    nombreequipo     VARCHAR (50) NOT NULL ,
    EQUIPO_idequipo  INTEGER NOT NULL ,
	CONSTRAINT JUGADOR_PK PRIMARY KEY ( nocamisola, EQUIPO_idequipo ) ,
	CONSTRAINT JUGADOR_EQUIPO_FK FOREIGN KEY ( EQUIPO_idequipo ) REFERENCES EQUIPO ( idequipo ) ON
	DELETE CASCADE
);

CREATE TABLE GRUPO (
    idgrupo INTEGER NOT NULL ,
    nombre  VARCHAR (50) NOT NULL ,
	CONSTRAINT GRUPO_PK PRIMARY KEY ( idgrupo ) ,
	CONSTRAINT GRUPO_NOMBRE_UN UNIQUE ( nombre )
);

CREATE TABLE ESTADISTICA (
    idestadistica INTEGER NOT NULL ,
    nombre        VARCHAR (50) NOT NULL ,
	CONSTRAINT ESTADISTICA_PK PRIMARY KEY ( idestadistica )
);

CREATE TABLE ASIGNACION_ESTADISTICA (
    JUGADOR_nocamisola        INTEGER NOT NULL ,
    ESTADISTICA_idestadistica INTEGER NOT NULL ,
    JUGADOR_EQUIPO_idequipo   INTEGER NOT NULL ,
    cantidad                  INTEGER NOT NULL ,
	CONSTRAINT ASIGNACION_ESTADISTICA_PK PRIMARY KEY ( JUGADOR_nocamisola, JUGADOR_EQUIPO_idequipo, ESTADISTICA_idestadistica ) ,
	CONSTRAINT ASIG_EST_EST_FK FOREIGN KEY ( ESTADISTICA_idestadistica ) REFERENCES ESTADISTICA ( idestadistica ) ON
	DELETE CASCADE ,
	CONSTRAINT ASIG_EST_JUGADOR_FK FOREIGN KEY ( JUGADOR_nocamisola, JUGADOR_EQUIPO_idequipo ) REFERENCES JUGADOR ( nocamisola, EQUIPO_idequipo ) ON
	DELETE CASCADE
);

CREATE TABLE ASIGNACION_GRUPO (
    GRUPO_idgrupo   INTEGER NOT NULL ,
    EQUIPO_idequipo INTEGER NOT NULL ,
	CONSTRAINT ASIGNACION_GRUPO_PK PRIMARY KEY ( GRUPO_idgrupo, EQUIPO_idequipo ) ,
	CONSTRAINT ASIGNACION_GRUPO_EQUIPO_FK FOREIGN KEY ( EQUIPO_idequipo ) REFERENCES EQUIPO ( idequipo ) ON
	DELETE CASCADE ,
	CONSTRAINT ASIGNACION_GRUPO_GRUPO_FK FOREIGN KEY ( GRUPO_idgrupo ) REFERENCES GRUPO ( idgrupo ) ON
	DELETE CASCADE
);

CREATE TABLE PARTIDO (
    EQUIPO_idequipo1  INTEGER NOT NULL ,
    EQUIPO_idequipo2 INTEGER NOT NULL ,
    fecha            DATE NOT NULL ,
    CIUDAD_idciudad  INTEGER NOT NULL ,
    equipo1          INTEGER NOT NULL ,
    equipo2          INTEGER NOT NULL ,
    tipo_final       VARCHAR (50) NOT NULL ,
	CONSTRAINT PARTIDO_PK PRIMARY KEY ( EQUIPO_idequipo1, EQUIPO_idequipo2, fecha ) ,
	CONSTRAINT PARTIDO_EQUIPO1_FK FOREIGN KEY ( EQUIPO_idequipo1 ) REFERENCES EQUIPO ( idequipo ) ,
	CONSTRAINT PARTIDO_EQUIPO2_FK FOREIGN KEY ( EQUIPO_idequipo2 ) REFERENCES EQUIPO ( idequipo ) ,
	CONSTRAINT PARTIDO_CIUDAD_FK FOREIGN KEY ( CIUDAD_idciudad ) REFERENCES CIUDAD ( idciudad )
);

CREATE TABLE PRONOSTICO (
    equipo1                     INTEGER NOT NULL ,
    equipo2                     INTEGER NOT NULL ,
    PARTICIPANTE_idparticipante INTEGER NOT NULL ,
    tipo_final                  VARCHAR (50) NOT NULL ,
    PARTIDO_idequipo1            INTEGER NOT NULL ,
    PARTIDO_idequipo2           INTEGER NOT NULL ,
    PARTIDO_fecha               DATE NOT NULL ,
    apuesta                     NUMERIC (10,2) NOT NULL ,
	CONSTRAINT PRONOSTICO_PK PRIMARY KEY ( PARTICIPANTE_idparticipante, PARTIDO_idequipo1, PARTIDO_idequipo2, PARTIDO_fecha ) ,
	CONSTRAINT PRONOSTICO_PARTICIPANTE_FK FOREIGN KEY ( PARTICIPANTE_idparticipante ) REFERENCES PARTICIPANTE ( idparticipante ) ON	DELETE CASCADE ,
	CONSTRAINT PRONOSTICO_PARTIDO_FK FOREIGN KEY ( PARTIDO_idequipo1, PARTIDO_idequipo2, PARTIDO_fecha ) REFERENCES PARTIDO ( EQUIPO_idequipo1, EQUIPO_idequipo2, fecha ) ON DELETE CASCADE
);

CREATE TABLE ASIGNACION_ARBITRO (
    ARBITRO_idarbitro INTEGER NOT NULL ,
    PARTIDO_idequipo1  INTEGER NOT NULL ,
    PARTIDO_idequipo2 INTEGER NOT NULL ,
    PARTIDO_fecha     DATE NOT NULL ,
    tipo_arbitro      VARCHAR (50) NOT NULL ,
    CONSTRAINT ASIGNACION_ARBITRO_PK PRIMARY KEY ( ARBITRO_idarbitro, PARTIDO_idequipo1, PARTIDO_idequipo2, PARTIDO_fecha ) ,
	CONSTRAINT ASIGNACION_ARBITRO_ARBITRO_FK FOREIGN KEY ( ARBITRO_idarbitro ) REFERENCES ARBITRO ( idarbitro ) ON DELETE CASCADE ,
	CONSTRAINT ASIGNACION_ARBITRO_PARTIDO_FK FOREIGN KEY ( PARTIDO_idequipo1, PARTIDO_idequipo2, PARTIDO_fecha ) REFERENCES PARTIDO ( EQUIPO_idequipo1, EQUIPO_idequipo2, fecha ) ON DELETE CASCADE
);